name: Example workflow

on: 
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: [self-hosted]

    steps:  
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t test-framework -f dockerfile .
      - name: Run tests
        run: |
          artifactPath="${{ github.workspace }}/artifact"
          mkdir -p $artifactPath

          echo "Run local tests"
          docker run -v "$artifactPath:/mnt/out" --rm test-framework --filter "Category=local"

          echo "Run internet tests"
          docker run -v "$artifactPath:/mnt/out" --rm test-framework --filter "Category=internet"

          echo "Generate living doc"
          docker run -v "$artifactPath:/mnt/out" --rm test-framework --run-tests false --generate-doc true

          echo "artifactPath=$artifactPath" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: ${{ env.artifactPath }}