name: Example CI workflow

on: 
  push:
    paths-ignore:
      - '**/README.md'
      - '**/example-test-runner-workflow.yml'

env:
  IMAGE: ${{ secrets.REGISTRY_LOGIN_SERVER }}/test-framework:ci-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v3

      - name: Login docker
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push image ${{ env.IMAGE }}
        run: |
          docker build --tag ${{ env.IMAGE }} --file dockerfile .
          docker push ${{ env.IMAGE }}