name: Example workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v3
      - name: build
        run: docker build -t test -f dockerfile .
      - name: test
        run: docker run -v "$RUNNER_TEMP:/mnt/results" -i --rm test --filter "Category=local | Category=internet & Category!=intranet"
      - name: display TestExecution.json content
        run: cat $RUNNER_TEMP/TestExecution.json